// Minimal, self-contained sanitize schema that allows
// common content (including lists and blockquotes) without
// importing the default schema to avoid Vite optimize issues.
export const sanitizeSchema = {
  strip: ['script', 'style'],
  clobberPrefix: 'user-content-',
  tagNames: [
    'a',
    'b',
    'strong',
    'i',
    'em',
    'u',
    's',
    'del',
    'span',
    'p',
    'br',
    'blockquote',
    'ul',
    'ol',
    'li',
    'code',
    'pre',
    'kbd',
    'samp',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'img',
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    // custom fenced outputs
    'x-fenced-card',
    'x-fenced-chart',
  ],
  attributes: {
    '*': ['title', 'dir', 'lang', 'xml:lang'],
    a: ['href', 'rel', 'target'],
    img: ['src', 'alt', 'title', 'width', 'height'],
    table: ['align'],
    thead: ['align'],
    tbody: ['align'],
    tfoot: ['align'],
    tr: ['align'],
    td: ['align', 'colspan', 'rowspan'],
    th: ['align', 'colspan', 'rowspan'],
    code: ['className'],
    pre: ['className'],
    'x-fenced-card': ['data-json'],
    'x-fenced-chart': ['data-json'],
  },
  protocols: {
    href: ['http', 'https', 'mailto'],
    src: ['http', 'https', 'data'],
  },
};
