name = "blog-recommendations"
main = "functions/blog-recommendations-worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "46de9e76f56041afbe5bb844e77fcc8c"
preview_id = "906df904193349a7983166eaec0b921b"

[env.production]
name = "blog-recommendations"
route = "blog-recommendations.your-domain.com/*"

[env.staging]
name = "blog-recommendations-staging"
route = "blog-recommendations-staging.your-domain.com/*"
