name = "content-search"
main = "workers/content-search-worker.ts"
compatibility_date = "2024-01-01"

# GitHub API configuration
[vars]
ENVIRONMENT = "production"
GITHUB_REPO = "rogerleecormier/tanstack-portfolio-content"
GITHUB_BRANCH = "main"
CONTENT_PATH = "src/content"
GITHUB_API_BASE = "https://api.github.com"

# GitHub API token (set this manually with: wrangler secret put GITHUB_TOKEN)
# secrets_store_secrets = [
#   { binding = "GITHUB_TOKEN", store_id = "04a2a114b7dc4068a7e8aad556011a8e", secret_name = "GithubAPIKey" }
# ]

# KV namespace for persistent content caching
[[kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

# Enable logging
[observability.logs]
enabled = true
