name = "tanstack-portfolio"
compatibility_date = "2024-09-25"

pages_build_output_dir = "dist"

# Enable Node.js compatibility for Pages Functions that use Node.js built-ins
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "tanstack-portfolio"
pages_build_output_dir = "dist"

[[env.production.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

# Preview environment (branch deployments)
[env.preview]
name = "tanstack-portfolio-preview"

[[env.preview.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"  # Same KV namespace for preview

# Add R2 binding for preview as well
[[env.preview.r2_buckets]]
binding = "R2_CONTENT"
bucket_name = "tanstack-portfolio-r2"

