name = "tanstack-portfolio"
compatibility_date = "2024-09-25"

pages_build_output_dir = "dist"

# Enable Node.js compatibility for Pages Functions that use Node.js built-ins
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "tanstack-portfolio"
pages_build_output_dir = "dist"


