name = "github-file-manager"
main = "workers/github-file-manager.ts"
compatibility_date = "2024-01-01"

# GitHub API configuration
[vars]
ENVIRONMENT = "production"
GITHUB_REPO = "rogerleecormier/tanstack-portfolio"
GITHUB_BRANCH = "content"
CONTENT_PATH = ""
GITHUB_API_BASE = "https://api.github.com"
COMMIT_AUTHOR_NAME = "Roger Lee Cormier"
COMMIT_AUTHOR_EMAIL = "rogerleecormier@gmail.com"

# Secrets from Cloudflare Secrets Store
secrets_store_secrets = [
  { binding = "GITHUB_TOKEN", store_id = "04a2a114b7dc4068a7e8aad556011a8e", secret_name = "GithubAPIKey" }
]

# Enable logging
[observability.logs]
enabled = true
