name = "tanstack-portfolio"
compatibility_date = "2024-01-01"

# Enable Node.js compatibility for Pages Functions
pages_build_output_dir = "dist"

# Enable Node.js compatibility for functions that use Node.js built-ins
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "tanstack-portfolio"
pages_build_output_dir = "dist"

[env.cloudflare-access-test]
name = "tanstack-portfolio-cloudflare-test"
pages_build_output_dir = "dist"

# Branch deployment configuration
[env.cloudflare-access-test.pages]
branch = "cloudflare-access-test"
