# Wrangler configuration for AI Contact Analyzer Worker
name = "ai-contact-analyzer"
main = "functions/ai-contact-analyzer.js"
compatibility_date = "2024-01-01"

# AI binding for Cloudflare AI
[ai]
binding = "ai"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
# Production environment - uses main worker

# Development environment
[env.development]
# Development environment - uses same production worker
# This allows dev to use the live production worker
vars = { ENVIRONMENT = "development" }

# Enable logging for all environments
[observability.logs]
enabled = true