name = "tanstack-portfolio-email-worker"
main = "functions/send-email.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Environment-specific configurations
[env.production]
# Production environment - uses main worker

[env.development]
# Development environment - uses same production worker
# This allows dev to use the live production worker

# Enable logging for all environments
[observability.logs]
enabled = true