name = "tanstack-portfolio"
compatibility_date = "2024-01-01"

[env.production]
name = "tanstack-portfolio"
pages_build_output_dir = "dist"

[env.cloudflare-access-test]
name = "tanstack-portfolio-cloudflare-test"
pages_build_output_dir = "dist"

# Branch deployment configuration
[env.cloudflare-access-test.pages]
branch = "cloudflare-access-test"
