name = "cache-rebuild-worker"
main = "../workers/cache-rebuild-worker.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
workers_dev = true

# Default KV Namespace for cache storage (production)
[[kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

# Default R2 Bucket for content source (production)
[[r2_buckets]]
binding = "R2_CONTENT"
bucket_name = "tanstack-portfolio-r2"

# Default environment variables
[vars]
ENVIRONMENT = "production"

# Environment configuration
[env.production]
name = "cache-rebuild-worker"

# KV Namespace for cache storage
[[env.production.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

# R2 Bucket for content source
[[env.production.r2_buckets]]
binding = "R2_CONTENT"
bucket_name = "tanstack-portfolio-r2"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"

# Cron triggers for automatic cache rebuilds
# Every 6 hours: 0 */6 * * *
# Daily at 3 AM UTC: 0 3 * * *
# Every 4 hours: 0 */4 * * *
[env.production.triggers]
crons = ["0 */4 * * *"]  # Every 4 hours

# Optional: API key for security (set via wrangler secret)
# wrangler secret put REBUILD_API_KEY --env production

# Preview environment (branch deployments)
[env.preview]
name = "cache-rebuild-worker-preview"

[[env.preview.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"  # Same KV namespace as production

[[env.preview.r2_buckets]]
binding = "R2_CONTENT"
bucket_name = "tanstack-portfolio-r2"

[env.preview.vars]
ENVIRONMENT = "preview"

# Cron triggers for preview (optional - less frequent)
[[env.preview.triggers]]
cron = "0 12 * * *"  # Daily at noon UTC for preview

# Development environment
[env.development]
name = "cache-rebuild-worker-dev"

[[env.development.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

[[env.development.r2_buckets]]
binding = "R2_CONTENT"
bucket_name = "tanstack-portfolio-r2"

[env.development.vars]
ENVIRONMENT = "development"
