name = "r2-content-full"
main = "../workers/r2-content-full.ts"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ALLOWED_DIRS = "blog,portfolio,projects"
MAX_FILE_BYTES = "1048576"

# R2 bucket bindings
[[r2_buckets]]
binding = "PORTFOLIO_CONTENT"
bucket_name = "tanstack-portfolio-r2"

# Enable logging for production
[observability.logs]
enabled = true