name = "health-bridge-d1-manager"
compatibility_date = "2024-01-01"

# D1 Database binding for health_bridge
[[d1_databases]]
binding = "DB"
database_name = "health_bridge"
database_id = "dd2b4664-fa2b-4534-8f07-3d1d0361ec06"

# Environment variables
[vars]
ENVIRONMENT = "development"
DATABASE_NAME = "health_bridge"

