# AI Contact Analyzer Worker Configuration for tanstack-portfolio
# Handles AI-powered contact form analysis and content recommendations

name = "tanstack-portfolio-ai-contact-analyzer"
main = "../workers/ai-contact-analyzer.js"
compatibility_date = "2024-01-01"

# AI binding for Cloudflare AI
[ai]
binding = "ai"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Enable logging for production
[observability.logs]
enabled = true
