name = "kv-cache-get"
main = "../workers/kv-cache-get.ts"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "kv-cache-get"

# KV Namespace binding for production
[[env.production.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"

# Enable logging for production
[env.production.observability.logs]
enabled = true

# Development environment (optional)
[env.development]
name = "kv-cache-get-dev"

# KV Namespace binding for development (same as production for consistency)
[[env.development.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "0acc4d15643a427aa6a88967083be65d"
